import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies, headers } from "next/headers";

import { redirect } from "next/navigation";
import { getServerAuthSession } from "~/server/auth";
import { TRPCReactProvider } from "~/trpc/react";
import ContextLayer from "./page";
import { getServerSideProps } from "next/dist/build/templates/pages";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  // console.log(getServerSideProps());
  const headersList = headers();
  const data = (headersList.get("x-current-path") ?? "not_loaded").split("/");
  const route = () => {
    return data[data.length - 1];
  };
  console.log(data, headersList);
  console.log("session", session);
  console.log(route());
  if (!session && route() !== "not_loaded" && route() !== "login") {
    redirect("/login");
  }

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <ContextLayer>{children}</ContextLayer>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
